apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
  name: "frontend-service"
spec:
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
    nodePort: 30444
  type: NodePort
  selector:
    app: "frontend-selector"
