apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
  name: "backend-service"
spec:
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
    nodePort: 30555
  type: NodePort
  selector:
    app: "backend-selector"
